### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by dezem** [eliboa/NxNandManager#17]
I think it's better for the emuMMC dump progress.
That the "FULL DUMP" dumps the boot0/boot1 and rawnand to three different files and not in one big file.

**Comment by eliboa** [comment]
Hi dezem and thank you for your suggestion.

You can already extract BOOT0 and BOOT1 from a "FULL NAND" dump (simply open then dump, then right clic on BOOT partition then select "Dump to file"). To extract RAWNAND from FULL NAND, you can use the "Dump RAWNAND only" from the "Options" menu.

I find that dumping emuMMC in a single file is safer because the user can't mix up files (wrong BOOT for RAWNAND) when restoring. Maybe I can find a more elegant way to split an emuMMC dump in three file, but I don't think I'll change tha way the program works natively.

**Comment by dezem** [comment]
Hi eliboa thanks for the fast reply.

Yes i know the menu section to dump only the rawnand file.
But on this way you have extra steps to get the complete dump.

If you dump the eMMC from the switch, you have also three files with the NXNandManager.
So why not at emuMMC the same principle?

Other tools are also dump it to different files, like hekate, sx os, emutool.

**Comment by eliboa** [comment]
With separate files, the additional steps you mentioned would still be needed, but this time when restoring.
I know this is arbitrary. It's the same for RAWNAND, it would have been possible to dump it in separate files (one for each partition : USER, PRODINFO, etc).
As I explained before, this is not something I plan to change, but I might change my mind if several users request it :smile:

**Comment by dezem** [comment]
It's ok, i can live with that.
If you like you can close it or let it open :-)

**Comment by eliboa** [comment]
I'll keep it open for now, in case someone wants to give his opinion on that matter 😉
